"""empty message

Revision ID: 92518294fbba
Revises: a6fbe3cb0030
Create Date: 2018-06-30 17:26:14.572441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92518294fbba'
down_revision = 'a6fbe3cb0030'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('link_url', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banner')
    # ### end Alembic commands ###
