"""empty message

Revision ID: 9478553d0fcc
Revises: 107651f551e7
Create Date: 2018-06-12 21:05:21.196610

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9478553d0fcc'
down_revision = '107651f551e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_role_user',
    sa.Column('cms_role_id', sa.Integer(), nullable=False),
    sa.Column('cms_user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cms_role_id'], ['cms_role.id'], ),
    sa.ForeignKeyConstraint(['cms_user_id'], ['cms_user.id'], ),
    sa.PrimaryKeyConstraint('cms_role_id', 'cms_user_id')
    )
    op.drop_table('cns_role_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cns_role_user',
    sa.Column('cms_role_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cms_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cms_role_id'], ['cms_role.id'], name='cns_role_user_ibfk_1'),
    sa.ForeignKeyConstraint(['cms_user_id'], ['cms_user.id'], name='cns_role_user_ibfk_2'),
    sa.PrimaryKeyConstraint('cms_role_id', 'cms_user_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('cms_role_user')
    # ### end Alembic commands ###
